name = "my-app"
compatibility_date = "2023-12-01"

[vars]
MY_VAR = "my-variable"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTY4OTg3NjktYTQ1OC00NzgwLTk0ZjItZDA4MTc0OWFjYWJmIiwidGVuYW50X2lkIjoiM2Q3OWNmNDlmY2Y4ZTVhOTA1ZDc0NWRiNmNiYjBjOGNhYzE3ZTcwMTZlYTA0OTQwMzk3MmI3OTMzNGRjNGU5MiIsImludGVybmFsX3NlY3JldCI6IjI3MDZlM2VjLTJlNjItNGFhNC05ZjFjLWZlNzI1NTNiNWMxYiJ9.vN7k8eMJQ9iLaRKAqfU0ZY4960wuF7UGTsn-7hmc51s"
JWT_SECRET = "mysecretpassword"

